NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 1
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 1
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 1
NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 1
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 1
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 1
NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST = 1
NDefines.NIndustrialOrganisation.DESIGN_TEAM_CHANGE_XP_COST = 1